name: C CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
     
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: make 🔨
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: download-linux
        path: bin/download